package life.picacg.community.community.mapper;

import java.util.List;
import life.picacg.community.community.model.Publish;
import life.picacg.community.community.model.PublishExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    long countByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    int deleteByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    int insert(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    int insertSelective(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    List<Publish> selectByExampleWithBLOBsWithRowbounds(PublishExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    List<Publish> selectByExampleWithBLOBs(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    List<Publish> selectByExampleWithRowbounds(PublishExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    List<Publish> selectByExample(PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    Publish selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") Publish record, @Param("example") PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Publish record, @Param("example") PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    int updateByExample(@Param("record") Publish record, @Param("example") PublishExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    int updateByPrimaryKeySelective(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Publish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLISH
     *
     * @mbg.generated Wed Jan 15 14:28:55 CST 2020
     */
    int updateByPrimaryKey(Publish record);
}